BACKEND_SELEZIONATO = '0'
STRINGA_PERCORSO_CSV = 'ottimizzazione_portafoglio/dati_confronto_4_asset.csv'
ARGOMENTO_PARSING_CSV = 'Unnamed: 0'
PREZZO_ASSET_1 = 50
PREZZO_ASSET_2 = 70
PREZZO_ASSET_3 = 25
PREZZO_ASSET_4 = 30
Q = 1 # propensione al rischio dell'investitore
BUDGET = 300
BOUNDS = [(0, 6), (0, 2), (0, 3), (0, 7)] 
BACKEND_LOCALE = 'qasm_simulator'
BACKEND_SIMULATORE_IBM = 'ibmq_qasm_simulator'
BACKEND_MACCHINA_REALE_IBM = 'ibmq_montreal'