BACKEND_SELEZIONATO = '0' # 0: locale; 1: simulatore remoto; 2: macchina reale
STRINGA_PERCORSO_CSV = 'ottimizzazione_portafoglio/dataset_piu_variabili.csv'
NUMERO_ASSET = 4 # il numero di colonne massimo è 7
ARGOMENTO_PARSING_CSV = 'Unnamed: 0'
OTTIMIZZATORE = 'cobyla' # lista: 'cobyla', 'spsa', 'adam'
LISTA_OTTIMIZZATORI = ['cobyla', 'spsa', 'powell']
PREZZO_ASSET_1 = 50
PREZZO_ASSET_2 = 70
PREZZO_ASSET_3 = 25
PREZZO_ASSET_4 = 30
PREZZO_ASSET_5 = 90
PREZZO_ASSET_6 = 15
PREZZO_ASSET_7 = 5
Q = 1 # propensione al rischio dell'investitore
BUDGET = 300
BOUNDS = [(0, 6), (0, 2), (0, 3), (0, 7), (0, 4), (0, 2), (0, 3)] 
BACKEND_LOCALE = 'qasm_simulator'
BACKEND_SIMULATORE_IBM = 'ibmq_qasm_simulator'
BACKEND_MACCHINA_REALE_IBM = 'ibmq_montreal'